version: '3.9'

services:
  web:
    build: 
      context: .
      target: development
    container_name: web
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: 
      - entrypoints/development.sh

  db:
    image: postgres:13.1-alpine
    container_name: db
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gems:
  postgres: